### ISSUE TITLE
Files access when installing package

### ISSUE THREAD

**Issue by mrudorfer** [mrudorfer/burg-toolkit#1]
Assets like gripper URDF files cannot be accessed when package is installed to site-packages.
To reproduce error install this package directly from github:
```
pip install git+https://github.com/mrudorfer/burg-toolkit.git@dev
```

Then loading a gripper in simulation:
```
import burg_toolkit as burg
import numpy as np

sim = burg.sim.GraspSimulator(burg.Scene(), verbose=True, plane_and_gravity=True)
gripper = burg.gripper.Franka(sim)
gripper.load(np.eye(4))
```

The error will be:
```
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,152]:

b3Printf: URDF file '/home/martin/dev/burg-toolkit/venv/lib/python3.6/site-packages/burg_toolkit/gripper/assets/franka/model.urdf' not found

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/dev/burg-toolkit/venv/lib/python3.6/site-packages/burg_toolkit/gripper/franka.py", line 31, in load
    baseOrientation=orientation
pybullet.error: Cannot load URDF file.
```

Checking the site-packages directory to which the toolkit has been installed, the asset folders are not there and hence the files cannot be found.
What is the best way to install the package including those files?

**Comment by mrudorfer** [comment]
It works now in the scenario described above, by adding package_data info in setup.py.
It might not work for other ways of distributing, especially when it is packaged up the files may not be physically accessible, and then retrieving them from within the package by relative path as is the case now will not work. Also there is a lot of confusion and ambiguity about how to make it work for all cases, see e.g. [here](https://stackoverflow.com/a/14159430).

Anyways, for now this is resolved (in dev branch).
